#!/bin/bash
#
#muutujate kasutamise näide
#
#defineerime muutuja ja omistame väärtuse
#väärtus saadakse whoami käsust
kasutaja=`whoami`
#väljastame muutuja väärtuse koos seletusega
echo "Tere, $kasutaja"
#loome ja väljastame kell
kell=`date +'%H:%M'`
echo "Kell on $kell"
