#!/bin/bash
#
#muutujate kasutamise näide
#
#defineerime muutuja ja omistame väärtuse
#väärtus saadakse whoami käsust
kasutaja=`whoami`
#väljastame muutuja väärtuse koos seletusega
echo "Tere, $kasutaja"
