#!/bin/bash
#
echo -n "Sisestage algusnumber:"
read algnumber
echo -n "Sisestage loppnumber:"
read loppnumber
#
for(( nr=algnumber; nr<=$loppnumber; nr++ ))
do
failinimi="fail$nr"
if [ -f $failinimi ]; then
	echo "$failinimi fail juba olemas"
	echo -n "Kas soovid asendada uue failiga? y/n"
	read vastus
	if [ "$vastus" = "y" -o "$vastus" = "Y" ]; then
	rm $failinimi
	touch $failinimi
fi
else
touch $failinimi
echo "$failinimi on loodud"
fi
done
