#!/bin/bash
# arvu pos/neg kt
#
# küsime väärtused kasutaja käest
echo -n "sisesta arv: "
read arv
# kontrollime, kas arv on pos
# sel juhul arv peab olema suurem kui 0
if [ $arv -gt 0 ]
then
	echo "$arv on pos"
# muidu kui väärtus in neg
# siis arv peab olema väiksem kui 0
elif [ $arv -lt 0 ]; then
	echo "$arv on neg"
# kui esimene tingimus
# või teine tingimus ei sobinud
# siis kasuta else osa
else
	echo "$arv on neutraalne"
# if lause tuleb korralikult lõpetada
fi
